### ISSUE TITLE
This is old and broken

### ISSUE THREAD

**Issue by mikeck1** [aboglioli/fullstack-graphql#3]
ERROR: for backend_mongo-express_1  Cannot start service mongo-express: driver failed programming external connectivity on endpoint backend_mongo-express_1

**Comment by aboglioli** [comment]
It's not old. You are facing docker-compose problems. **mongo-express** is set up on 8080 port. Maybe that port is being used in your computer by another service. Try to change it.

Copy `backend/.env.sample` to `backend/.env`. In that file you can change ports used in docker-compose.
